"""empty message

Revision ID: 12130e04d23f
Revises: e541d2289df8
Create Date: 2018-11-28 14:44:52.272664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12130e04d23f'
down_revision = 'e541d2289df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    # ### end Alembic commands ###
