"""empty message

Revision ID: 79deb731026c
Revises: 12130e04d23f
Create Date: 2018-11-28 15:05:38.643724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79deb731026c'
down_revision = '12130e04d23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_constraint('donation_transaction_id_fkey', 'donation', type_='foreignkey')
    op.create_foreign_key(None, 'donation', 'image', ['image_id'], ['id'])
    op.drop_column('donation', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'donation', type_='foreignkey')
    op.create_foreign_key('donation_transaction_id_fkey', 'donation', 'image', ['transaction_id'], ['id'])
    op.drop_column('donation', 'image_id')
    # ### end Alembic commands ###
