"""created images

Revision ID: e541d2289df8
Revises: e7c6bc98c2f5
Create Date: 2018-11-26 15:46:24.611237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e541d2289df8'
down_revision = 'e7c6bc98c2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'private')
    op.drop_column('user', 'description')
    op.drop_table('image')
    # ### end Alembic commands ###
